AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - './spec/*_spec.rb'

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

## Offense count: 13
Metrics/LineLength:
  Max: 99

Gemspec/RequiredRubyVersion:
  Enabled: false
